const products = [
  {
    id: 1,
    title: 'М-50',
    type: 'panel',
    description: 'Габаритные размеры 165х143х22 мм. Покрываемая площадь 0,011788 кв.м ВАЖНО! Калькулятор на нашем сайте высчитывает стоимость одной панели и количество панелей под Ваши размеры автоматически. Стоимость одной панели линейки Modern M-50 составляет 41,97 руб. Также, из-за не квадратной формы панели, пожалуйста, воспользуйтесь помощью нашего специалиста для расчета точного количества панелей на Вашу плоскость. Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: '165х143х22 мм',
    price: '83.99 Р/шт',
    imageURL: 'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/product/background/107/products_becgrund.jpg',
    images: [
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    ],
  },
  {
    id: 2,
    title: 'М-50',
    type: 'panel',
    description: 'Габаритные размеры 165х143х22 мм. Покрываемая площадь 0,011788 кв.м ВАЖНО! Калькулятор на нашем сайте высчитывает стоимость одной панели и количество панелей под Ваши размеры автоматически. Стоимость одной панели линейки Modern M-50 составляет 41,97 руб. Также, из-за не квадратной формы панели, пожалуйста, воспользуйтесь помощью нашего специалиста для расчета точного количества панелей на Вашу плоскость. Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: '165х143х22 мм',
    price: '83.99 Р/шт',
    imageURL: 'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/product/background/107/products_becgrund.jpg',
    images: [
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    ],
  },
  {
    id: 3,
    title: 'М-50',
    type: 'panel',
    description: 'Габаритные размеры 165х143х22 мм. Покрываемая площадь 0,011788 кв.м ВАЖНО! Калькулятор на нашем сайте высчитывает стоимость одной панели и количество панелей под Ваши размеры автоматически. Стоимость одной панели линейки Modern M-50 составляет 41,97 руб. Также, из-за не квадратной формы панели, пожалуйста, воспользуйтесь помощью нашего специалиста для расчета точного количества панелей на Вашу плоскость. Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: '165х143х22 мм',
    price: '83.99 Р/шт',
    imageURL: 'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/product/background/107/products_becgrund.jpg',
    images: [
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    ],
  },
  {
    id: 4,
    title: 'М-50',
    type: 'panel',
    description: 'Габаритные размеры 165х143х22 мм. Покрываемая площадь 0,011788 кв.м ВАЖНО! Калькулятор на нашем сайте высчитывает стоимость одной панели и количество панелей под Ваши размеры автоматически. Стоимость одной панели линейки Modern M-50 составляет 41,97 руб. Также, из-за не квадратной формы панели, пожалуйста, воспользуйтесь помощью нашего специалиста для расчета точного количества панелей на Вашу плоскость. Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: '165х143х22 мм',
    price: '83.99 Р/шт',
    imageURL: 'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/product/background/107/products_becgrund.jpg',
    images: [
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    ],
  },
  {
    id: 5,
    title: 'М-50',
    type: 'panel',
    description: 'Габаритные размеры 165х143х22 мм. Покрываемая площадь 0,011788 кв.м ВАЖНО! Калькулятор на нашем сайте высчитывает стоимость одной панели и количество панелей под Ваши размеры автоматически. Стоимость одной панели линейки Modern M-50 составляет 41,97 руб. Также, из-за не квадратной формы панели, пожалуйста, воспользуйтесь помощью нашего специалиста для расчета точного количества панелей на Вашу плоскость. Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: '165х143х22 мм',
    price: '83.99 Р/шт',
    imageURL: 'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/product/background/107/products_becgrund.jpg',
    images: [
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    ],
  },
  {
    id: 6,
    title: 'М-50',
    type: 'panel',
    description: 'Габаритные размеры 165х143х22 мм. Покрываемая площадь 0,011788 кв.м ВАЖНО! Калькулятор на нашем сайте высчитывает стоимость одной панели и количество панелей под Ваши размеры автоматически. Стоимость одной панели линейки Modern M-50 составляет 41,97 руб. Также, из-за не квадратной формы панели, пожалуйста, воспользуйтесь помощью нашего специалиста для расчета точного количества панелей на Вашу плоскость. Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: '165х143х22 мм',
    price: '83.99 Р/шт',
    imageURL: 'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/product/background/107/products_becgrund.jpg',
    images: [
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    ],
  },
  {
    id: 7,
    title: 'М-50',
    type: 'panel',
    description: 'Габаритные размеры 165х143х22 мм. Покрываемая площадь 0,011788 кв.м ВАЖНО! Калькулятор на нашем сайте высчитывает стоимость одной панели и количество панелей под Ваши размеры автоматически. Стоимость одной панели линейки Modern M-50 составляет 41,97 руб. Также, из-за не квадратной формы панели, пожалуйста, воспользуйтесь помощью нашего специалиста для расчета точного количества панелей на Вашу плоскость. Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: '165х143х22 мм',
    price: '83.99 Р/шт',
    imageURL: 'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/product/background/107/products_becgrund.jpg',
    images: [
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    ],
  },
  {
    id: 8,
    title: 'М-50',
    type: 'panel',
    description: 'Габаритные размеры 165х143х22 мм. Покрываемая площадь 0,011788 кв.м ВАЖНО! Калькулятор на нашем сайте высчитывает стоимость одной панели и количество панелей под Ваши размеры автоматически. Стоимость одной панели линейки Modern M-50 составляет 41,97 руб. Также, из-за не квадратной формы панели, пожалуйста, воспользуйтесь помощью нашего специалиста для расчета точного количества панелей на Вашу плоскость. Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: '165х143х22 мм',
    price: '83.99 Р/шт',
    imageURL: 'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/product/background/107/products_becgrund.jpg',
    images: [
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    ],
  },
  {
    id: 9,
    title: 'М-50',
    type: 'panel',
    description: 'Габаритные размеры 165х143х22 мм. Покрываемая площадь 0,011788 кв.м ВАЖНО! Калькулятор на нашем сайте высчитывает стоимость одной панели и количество панелей под Ваши размеры автоматически. Стоимость одной панели линейки Modern M-50 составляет 41,97 руб. Также, из-за не квадратной формы панели, пожалуйста, воспользуйтесь помощью нашего специалиста для расчета точного количества панелей на Вашу плоскость. Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: '165х143х22 мм',
    price: '83.99 Р/шт',
    imageURL: 'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/product/background/107/products_becgrund.jpg',
    images: [
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    ],
  },
  {
    id: 10,
    title: 'М-50',
    type: 'panel',
    description: 'Габаритные размеры 165х143х22 мм. Покрываемая площадь 0,011788 кв.м ВАЖНО! Калькулятор на нашем сайте высчитывает стоимость одной панели и количество панелей под Ваши размеры автоматически. Стоимость одной панели линейки Modern M-50 составляет 41,97 руб. Также, из-за не квадратной формы панели, пожалуйста, воспользуйтесь помощью нашего специалиста для расчета точного количества панелей на Вашу плоскость. Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: '165х143х22 мм',
    price: '83.99 Р/шт',
    imageURL: 'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/product/background/107/products_becgrund.jpg',
    images: [
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
      'https://decoproduct.ru/uploads/product/cover/107/cover_M-50-1.jpg',
    ],
  },
  {
    id: 11,
    title: 'B-01',
    type: 'basreliefs',
    description: 'Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: 'Размер по заказу',
    price: '18300.0 Р/м2',
    imageURL: 'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/basrelief/background/1/products_becgrund-2.jpg',
    images: [
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    ],
  },
  {
    id: 12,
    title: 'B-01',
    type: 'basreliefs',
    description: 'Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: 'Размер по заказу',
    price: '18300.0 Р/м2',
    imageURL: 'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/basrelief/background/1/products_becgrund-2.jpg',
    images: [
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    ],
  },
  {
    id: 13,
    title: 'B-01',
    type: 'basreliefs',
    description: 'Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: 'Размер по заказу',
    price: '18300.0 Р/м2',
    imageURL: 'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/basrelief/background/1/products_becgrund-2.jpg',
    images: [
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    ],
  },
  {
    id: 14,
    title: 'B-01',
    type: 'basreliefs',
    description: 'Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: 'Размер по заказу',
    price: '18300.0 Р/м2',
    imageURL: 'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/basrelief/background/1/products_becgrund-2.jpg',
    images: [
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    ],
  },
  {
    id: 15,
    title: 'B-01',
    type: 'basreliefs',
    description: 'Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: 'Размер по заказу',
    price: '18300.0 Р/м2',
    imageURL: 'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/basrelief/background/1/products_becgrund-2.jpg',
    images: [
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    ],
  },
  {
    id: 16,
    title: 'B-01',
    type: 'basreliefs',
    description: 'Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: 'Размер по заказу',
    price: '18300.0 Р/м2',
    imageURL: 'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/basrelief/background/1/products_becgrund-2.jpg',
    images: [
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    ],
  },
  {
    id: 17,
    title: 'B-01',
    type: 'basreliefs',
    description: 'Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: 'Размер по заказу',
    price: '18300.0 Р/м2',
    imageURL: 'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/basrelief/background/1/products_becgrund-2.jpg',
    images: [
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    ],
  },
  {
    id: 18,
    title: 'B-01',
    type: 'basreliefs',
    description: 'Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: 'Размер по заказу',
    price: '18300.0 Р/м2',
    imageURL: 'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/basrelief/background/1/products_becgrund-2.jpg',
    images: [
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    ],
  },
  {
    id: 19,
    title: 'B-01',
    type: 'basreliefs',
    description: 'Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: 'Размер по заказу',
    price: '18300.0 Р/м2',
    imageURL: 'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/basrelief/background/1/products_becgrund-2.jpg',
    images: [
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    ],
  },
  {
    id: 20,
    title: 'B-01',
    type: 'basreliefs',
    description: 'Модель изготовлена из специального гипсового раствора с армирующими добавками. Итальянская технология производства. Является 100% экологически чистым продуктом, имеет уникальные свойства шумо-теплоизоляции. Абсолютно пожаробезопасен.',
    dimensions: 'Размер по заказу',
    price: '18300.0 Р/м2',
    imageURL: 'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    bgImage: 'https://decoproduct.ru/uploads/basrelief/background/1/products_becgrund-2.jpg',
    images: [
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
      'https://decoproduct.ru/uploads/basrelief/cover/1/cover_B-01-1.jpg',
    ],
  },
];

export default products;
